[client]
showSidebarNavigation = false

[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
primaryColor = "#5848d5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#5848d5"
textColor = "#0d0c52"
linkColor = "#5848d5"
borderColor = "#5848d5"
showWidgetBorder = true
baseRadius = "1.00rem"
buttonRadius = "full"
font = "SpaceGrotesk"
headingFontWeights = [600,500,500,500,500,500]
headingFontSizes = ["3rem", "2rem"]
codeFont = "SpaceMono"
codeFontSize = ".75rem"
codeBackgroundColor = "#3b3b3b"
showSidebarBorder = true
chartCategoricalColors = ["#05dde3", "#21c7f9", "#faeaa5"]

[theme.sidebar]
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#5848d5"
headingFontSizes = ["1.6rem", "1.4rem", "1.2rem"]
dataframeHeaderBackgroundColor = "#3b3b3b"